### ISSUE TITLE
Function name

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#10]
Really cool to see https://inbo.github.io/camtrapdp/articles/visualize-number-of-species-per-deployment.html!

Regarding the function name `visualize_species_per_deployment()`: it is really long! Depending on what other functions you are envisioning, can I suggest:

```
map_species()
map_dep()
plot_dep()
```

**Comment by jimcasaer** [comment]
I would suggest to go for map_dep(), this allows to broaden the scope of the function and use parameters to determine the characteristic of the deployment you want to show

**Comment by damianooldoni** [comment]
Great! Yes, choosing (short) names has never been my strong point. Thanks, guys to help me. I will change it to map_dep() an include the number of species as one of the possibilities in next PR.

**Comment by damianooldoni** [comment]
map_dep() used. Issue can be closed.
