### ISSUE TITLE
Group update metadata functions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#103]
## Create helper function `update_spatial()`

- [x] In `update_metadata.R`
- [x] Functionality is like [build_spatial() ](https://github.com/inbo/camtrapdp/pull/100/files#diff-60bef5af43a1bd541299ce9bceeb226afb23deaa5e637b145c85e05ffd552b0c)
- [x] Call function in `filter_deployments()`
- [x] Test by calling `filter_deployments()` (rather than testing the helper function directly)

## Create helper function `update_temporal()`

- [x] In `update_metadata.R`
- [x] Use functionality from https://github.com/inbo/camtrapdp/blob/aa600500939c32c01b1d002e4d284b73b365f741/R/filter_deployments.R#L66-L80
- [x] Call function in `filter_deployments()`
- [x] Test by calling `filter_deployments()` (rather than testing the helper function directly)

## Create helper function `update_taxonomic()`

- [x] In `update_metadata.R`
- [x] Use functionality from https://github.com/inbo/camtrapdp/blob/c55cf9e3ce1634d7d17caaacd8f1a7e4b1df1816/R/filter_media.R#L71-L75
- [x] Extra: when `taxonomic` is `NULL` create one (just the scientificNames)
- [x] Test by calling `filter_media()` and `filter_observations()` (rather than testing the helper function directly)

## Rename helper function `build_taxonomy()`

It currently sounds like this function is creating the metadata, while it is deriving a df from `taxonomic.

- [x] Rename to `build_taxa()` (or other suggestions)
- [x] Rename file and test file
- [x] Update calls to this function

All this can be implemented in #100. I will merge #89 into #100 first.

**Comment by sannegovaert** [comment]
_when taxonomic is NULL create one (just the scientificNames)_
Which format should this be?

A list of lists? 
```
[[1]]
[[1]]$scientificName
[1] "Anas platyrhynchos"

[[2]]
[[2]]$scientificName
[1] "Anas strepera"
```
A character vector? Or something else?
`[1] "Anas platyrhynchos"  "Anas strepera" `

**Comment by peterdesmet** [comment]
A list of lists, so that the json looks like this:

```json
"taxonomic": [
    {
      "scientificName": "Anas platyrhynchos"
    },
    {
      "scientificName": "Anas strepera"
    }
]
```
