### ISSUE TITLE
`round_coordinates()` does not identify the correct number of digits

### ISSUE THREAD

**Issue by sannegovaert** [inbo/camtrapdp#104]
The regular expression is not working as is meant to: https://github.com/inbo/camtrapdp/blob/96d004ad4652fd6b10b8b3ac8b35b664671eb6da/R/round_coordinates.R#L107

**Comment by peterdesmet** [comment]
Can you look into solving this? Odd that it wasn't captured in a test.

**Comment by peterdesmet** [comment]
I think we need the following:

``` r
lat0 <- 1.000
lat1 <- 1.90000
lat2 <- 139.94
lat3 <- 10.943

regex <- "^\\d*."

nchar(gsub(regex, "", lat0))
#> [1] 0
```

``` r
nchar(gsub(regex, "", lat1))
#> [1] 1
```

``` r
nchar(gsub(regex, "", lat2))
#> [1] 2
```

``` r
nchar(gsub(regex, "", lat3))
#> [1] 3
```

<sup>Created on 2024-07-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
