### ISSUE TITLE
Update scopes in metadata for assignment functions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#111]
When users update data using an assignment functions (e.g. `observations()<-`), the scopes in the metadata should likely be updated too. Doing so will directly also raise errors if odd things were assigned.

- [x] `deployments()<-`: `update_spatial()`, `update_temporal()`
- [x] `media()<-`: no action
- [x] `observations()<-`: `update_taxonomic()`

1. Note however, that the assignment functions are also used internally by other functions, so we have to make sure metadata is not updated twice. E.g. lines 66-70 can be removed here:

https://github.com/inbo/camtrapdp/blob/0fa8701e14221762d4c18e7a45e499227fb746d9/R/filter_deployments.R#L61-L73

2. The assignment functions would need tests too, but most of the functionality is already covered in the filter tests, so it can be minimal.

**Comment by sannegovaert** [comment]
+ `update_spatial()` should set $type <- "Polygon".
