### ISSUE TITLE
Use scientificNameID

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#12]
Rather than `taxonID` it is likely better to use `scientificNameID` (see https://github.com/tdwg/camtrap-dp/issues/340) and maybe to prepend it to make a full URL like https://www.catalogueoflife.org/data/taxon/GCHS (not sure that can be made programmatically)

**Comment by peterdesmet** [comment]
The conclusion of https://github.com/tdwg/camtrap-dp/issues/340 was that `package.taxonomic.taxonID` is a `dwc:taxonID`. The term now contains a full link, so no prepending is needed and the term does not need to be mapped to `scientificNameID`.

**Comment by sannegovaert** [comment]
> The conclusion of [tdwg/camtrap-dp#340](https://github.com/tdwg/camtrap-dp/issues/340) was that `package.taxonomic.taxonID` is a `dwc:taxonID`. The term now contains a full link, so no prepending is needed and the term does not need to be mapped to `scientificNameID`.

So this issue can be closed?

**Comment by peterdesmet** [comment]
Yes. If Camtrap DPs ever get published to GBIF, it will likely come up again (since `scientificNameID` is a required term there, cf. movepub), but we don't need to tackle this now.
