### ISSUE TITLE
Use contributor with role `contact` for contact and metadata provider in `write_eml()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#127]
We currently use the first creator for contact and metadata provider:

https://github.com/inbo/camtrapdp/blob/0c3ac25d1220230a770ee9795a49b963625995f0/R/write_eml.R#L27-L28

In my opinion we should pick all contributors with role `contact` for both terms. If no such contributors exist, fall back to the first creator. This can probably be achieved with a purrr function, similar to:

https://github.com/inbo/camtrapdp/blob/0c3ac25d1220230a770ee9795a49b963625995f0/R/write_eml.R#L147-L149

**Comment by sannegovaert** [comment]
`EML::set_responsibleParty()` doesn't have a parameter for role, so filtering on `role == contact` needs to happen earlier. I have now done it [this way](https://github.com/inbo/camtrapdp/pull/134/commits/69de6da53bc762b40584daf400026883e064317e), but it repeats some code. We could leave it like this, make it a helper function or come up with an alternative.
