### ISSUE TITLE
Add type, subtype and update frequency to EML in `write_eml()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#128]
- [ ] Use EML functions where possible
- [x] type (`Occurrence`) as:

```xml
<keywordSet>
   <keyword>Occurrence</keyword>
   <keywordThesaurus>GBIF Dataset Type Vocabulary: http://rs.gbif.org/vocabulary/gbif/dataset_type_2015-07-10.xml</keywordThesaurus>
</keywordSet>
```

- [x] subtype (`Observation`) as:

```xml
<keywordSet>
  <keyword>Observation</keyword>
  <keywordThesaurus>GBIF Dataset Subtype Vocabulary: http://rs.gbif.org/vocabulary/gbif/dataset_subtype.xml</keywordThesaurus>
</keywordSet>
```

- [x] update frequency (`unknown`)  as (the empty `description` is required):

```xml
<maintenance>
  <description>
    <para></para>
  </description>
  <maintenanceUpdateFrequency>unknown</maintenanceUpdateFrequency>
</maintenance>
```

- [x] Update documentation:

https://github.com/inbo/camtrapdp/blob/0c3ac25d1220230a770ee9795a49b963625995f0/R/write_eml.R#L42-L44

**Comment by sannegovaert** [comment]
I implemented this, and it looks the same in the eml output:
![image](https://github.com/user-attachments/assets/4ee6320c-6f1b-445f-a77d-1f712bbb798c)

But on the IPT, `type` is set but `subtype` is not set.

![image](https://github.com/user-attachments/assets/dfa0a768-ba0b-4a2c-a660-11bc86f3a9ae)

**Comment by peterdesmet** [comment]
Talked with @mike-podolskiy90 about this:

1. update frequency is a required EML field and should therefore be added

2. type and subtype (as a keywords) are:

- Not required EML field
- Ignored by IPT when you upload an eml
- Ignored by GBIF processing

There is no harm in adding them though.
