### ISSUE TITLE
Fix NOTES

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#144]
We currently have 3 NOTES, which are the result of global assignments:

```
❯ checking R code for possible problems ... NOTE
  taxa: no visible binding for global variable ‘.’
  taxa: no visible binding for global variable ‘columns_with_info’
  write_eml: no visible binding for global variable ‘role’
  Undefined global functions or variables:
    . columns_with_info role
```

**Comment by sannegovaert** [comment]
There seems to be a conflict between the R CMD check and tidyselect
By adding .data$ [here](https://github.com/inbo/camtrapdp/blob/99f8bc3b2914ce5b045a9703e2a6560a89f8b6ec/R/taxa.R#L51), the R CMD check note is fixed. But, instead we get dozens of tidyselect warnings:
```
Warning (test-check_camtrapdp.R:3:3): check_camtrapdp() returns an invisible camtrapdp object when valid
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
i Please use `"columns_with_info"` instead of `.data$columns_with_info`
```
So I don't understand where the R CMD check note is coming from.

**Comment by peterdesmet** [comment]
@PietrH or @damianooldoni can probably help to debug this.

**Comment by sannegovaert** [comment]
> There seems to be a conflict between the R CMD check and tidyselect. By adding .data$ [here](https://github.com/inbo/camtrapdp/blob/99f8bc3b2914ce5b045a9703e2a6560a89f8b6ec/R/taxa.R#L51), the R CMD check note is fixed. But, instead we get dozens of tidyselect warnings:
> 
> ```
> Warning (test-check_camtrapdp.R:3:3): check_camtrapdp() returns an invisible camtrapdp object when valid
> Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
> i Please use `"columns_with_info"` instead of `.data$columns_with_info`
> ```
> 
> So I don't understand where the R CMD check note is coming from.

It's fixed in this [commit](https://github.com/inbo/camtrapdp/pull/146/commits/accc38e847db02cbf09d005c67b91985676bf79b).
It is not intuitive to me when to use quoation marks with dplyr functions and when not to...

**Comment by PietrH** [comment]
It can be quite confusing. I can get back to this when I'm back from the workshop, in the meantime it might help to look at [this](https://rlang.r-lib.org/reference/args_data_masking.html) help page about _data-masking_, which is part of _tidy evaluation_ (Non standard evaluation) vs column selecting via tidyselect: https://dplyr.tidyverse.org/reference/select.html

In dplyr,
-  if  you see `<tidyselect>` you are selecting a column by position, via string matching = tidyselect, eg: `dplyr::select(.x, tidyselect::contains("string"))`
- If you see `<datamasking>` you are selecting via a logical value generated by an expression, eg. `dplyr::filter(.x, .data$column == "string")`

There was a blog post about the usage of `.data$` somewhere, but I can't find it at the moment.
