### ISSUE TITLE
Add `convert_to` argument to `read_camtrap_dp()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#16]
Scenario:

1. A new version of Camtrap DP comes out (1.1)
2. `camtrapdp::read_camtrap_dp()` is updated to support this latest version and upconverts 1.0 to 1.1
3. camtraptor, which uses camtrapdp as a dependency now breaks, because `read_camtrap_dp()` no longer returns the version (1.0) camtraptor expects internally

@PietrH @damianooldoni I assume camtraptor can control this by defining `camtrapdp == <working version>` in its DESCRIPTION? Is this annoying for users install the package?

Alternatively, `read_camtrap_dp(file, convert_to = "1.0")` has a parameter `convert_to` so other packages can control to which version `read_camtrap_dp()` is allowed to convert?

**Comment by damianooldoni** [comment]
Very interesting question/scenario!

Installing a new version of camtrapdp is not really annoying for a user of camtraptor as I don't expect a new version daily 😄 The point is that things will break suddenly: annoying for both users and maintainers.

👍 for the alternative solution: it will allow other packages (e.g. camtraptor) to (down)convert and so decide to change when it fits best. A typical scenario: researchers using camtraptor seem to use it more often in the autumn than in winter/spring: a change of the version of the data package could be nefast for their research. So, we could think to postpone the upgrade to a less busy moment and also allow us to better communicate to our users.

**Comment by peterdesmet** [comment]
Todo as part of this feature: block downconversion of datasets.

**Comment by PietrH** [comment]
`read_camtrap_dp(file, convert_to = "1.0")`

What if `convert_to` is not provided?

**Comment by peterdesmet** [comment]
Then it will default to `1.0` for the current version of camtrapdp.
