### ISSUE TITLE
Add taxonomic info to observations

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtrapdp#17]
It's handy to have taxonomy as a data.frame while reading a camtrap DP. Merging it to observations is something we would do in camtraptor (see inbo/camtraptor#234), not here.

**Comment by peterdesmet** [comment]
No, I would not have `taxonomy()` function in both camtrapdp and camtraptor, with slightly different functionality. We should have one in camtrapdp and it should just return the `package$taxonomy` as a data.frame. That information can be merged with `observations` by another function or other packages.

**Comment by damianooldoni** [comment]
Agreed. Quite confusing.
A possible solution could also be to call this function `build_taxonomy()` in camtrapdp? Reason: the taxonomy data.frame is for the first time **built** from the nested list. The point is that the function name `taxonomy()` fits very well in camtraptor as well , next to functions like `observations()`, `deployments()` etc.

**Comment by peterdesmet** [comment]
See #18 I would move `observations()`, `deployments()`, etc. to camtrapdp.

**Comment by peterdesmet** [comment]
This is implemented as part of #27. And that information is attached to the observations in `read_camtrapdp()` so it is available as part for `taxa()` #38.
