### ISSUE TITLE
get_n_obs => create table for one or several species

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#17]
allow possibility to run get_n_obs but select first one or several species 

- [x] allow possibility to run get_n_obs but select first one or several species 

- [x] default value is "all species"
- [x] use of latin or common names
- [x] e.g. get_n_obs(data, c("roe deer","wild boar","wolf")
- [x] ignore case

returns a table having deployment_id, species_1, species_2, ... as columns and n (nubmer of observations of a species in a deployment as value)

**Comment by damianooldoni** [comment]
I agree on all points except the returned data.frame. Your proposal is not tidy :no_good: 

I strongly suggest the following tidy structure:

deployment_id | species | n
-- | -- | --
dep_1 |  A | 1
dep_1 | B | 5
dep_2 | A | 4
dep_2 | C | 8
dep_3 | A | 2

**Comment by jimcasaer** [comment]
right yes !

**Comment by damianooldoni** [comment]
This issue has been solved. See `?get_n_obs` for examples and documentation.
