### ISSUE TITLE
Camtrap DP object

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#19]
I think the camtrapdp package should return a dedicated camtrapdp **object**, rather than `package` (see #18). It is very similar to `package` as returned by `frictionless::read_package()` but also contains dataframes in `object$data` and maybe some custom attributes.

## Name

The name of the object could be `camtrapdp`, `camtrap_dp`, `dataset` or `package`. The same name is ideally used for a custom class (cf. `tbl_df`), parameter names and documentation:

### camtrapdp

- Object: `camtrapdp`
- Class: `c("camtrapdp", "list")`
- Parameter: `deployments(camtrapdp)`
- Documentation: Derived from `camtrapdp$taxonomy`
- Remark: Short, same as package name (could be good or bad).

### camtrap_dp

- Object: `camtrap_dp`
- Class: `c("camtrap_dp", "list")` (cf. `tbl_df`)
- Parameter: `deployments(camtrap_dp)`
- Documentation: Derived from `camtrap_dp$taxonomy`
- Remark: Follows snake naming convention.

### dataset

- Object: `dataset`
- Class: `c("camtrap_dp", "list")` Would not use `dataset` here.
- Parameter: `deployments(dataset)`
- Documentation: Derived from `dataset$taxonomy`
- Remark: Too generic?

### package

- Object: `package`, even though it is a package with attached data, so more than a frictionless::package object
- Class: `c("camtrap_dp", "list")` Would not use `package` here.
- Parameter: `deployments(package)`
- Documentation: Derived from `package$taxonomy`
- Remark: Can be confused with R pkg. Indicates that it's (still) a frictionless::package, but that might be not be necessary to know for most users.

`camtrap_dp` looks like the most logical one, but overusing the Camtrap DP/camtrapdp/camtrap-dp/camtrap_dp name can be confusing too.

## Attributes

I'm tempted to add custom attributes to the class. Even though the Camtrap DP version can be derived from `object$profile`, I think it would be good to have it in a dedicated attribute:

```R
#> attr(dataset, "version")
"1.0"
```

@PietrH @damianooldoni @sangovae thoughts?

**Comment by damianooldoni** [comment]
Having such dedicated object is definitely a good idea, @peterdesmet 👍  
The main reason is that a camtrap DP is a frictionless package, but not all frictionless packages are camtrap DPs.

I vote for the first option: I find it very straightforward and sounds me very natural and easy to remember.

I agree on `c("camtrapdp", "list")`, but I would expect `c("camtrapdp", "fricitonless_package", "list")`, i.e. a frictionless dedicated object as output of `frictionless::read_package()`. Doing so, we build the class step by step as frictionless packages are a subset of lists (not all lists are frictionless packages of course) as camtrap DPs are a subset of frictionless data packages.

**Comment by peterdesmet** [comment]
Ok, I'm fine with choosing `camtrapdp` as the name throughout.

Regarding the class: frictionless doesn't add a custom class, there has currently not been a need for it. If useful, it should be argued as a feature for frictionless; don't think camtrapdp should add that class.

**Comment by damianooldoni** [comment]
Totally agree: camtrapdp shouldn't add it. It was more a general thought popping out by matter of consistency and of course a frictionless feature.

**Comment by peterdesmet** [comment]
Regarding the parameter name, do you prefer `camtrapdp` or `x`? I'm tempted to go for x as the central parameter.

**Comment by PietrH** [comment]
I quite like `x`, but explain further in argument documentation

**Comment by peterdesmet** [comment]
Implemented as part of #15:

https://github.com/inbo/camtrapdp/blob/df66f087f0ec8deb35459b0fb85c7d56b747d221/R/read_camtrap_dp.R#L26-L29

**Comment by PietrH** [comment]
I'll leave that up to Sanne to review. 

What made you choose `x`?

**Comment by peterdesmet** [comment]
I choose `x` as it is also how `dplyr()` or `tibble()` (and `bioRad`) work with their central object that is passed around from function to function.

**Comment by PietrH** [comment]
Fair enough! Good to know

**Comment by damianooldoni** [comment]
I agree too. Nice idea ⚡  it is also shorter, easy to remember and the best name for straightforward arguments.
