### ISSUE TITLE
Create `check_camtrapdp()` function

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#21]
Checks if an object is indeed a camtrapdp object. Inspiration: https://github.com/frictionlessdata/frictionless-r/blob/main/R/check_package.R

- [x] Does it have the class `c("camtrapdp" "list")`
- [x] Call the function from `observations()`, `deployments()`, `media()`
- [ ] ~Is the used version supported? This functionality could be provided by having a `version` attribute~
- [x] Also call `check_package()`, see #33 

```R
#> check(x = my_camtrap_dp, version = "1.0")
error: x is does not have the expected version 1.0
```

**Comment by damianooldoni** [comment]
Should we start thinking about verbosity here?
I suppose `check()` can be used inside functions like `deployments()` or `locations()` with nothing returned if checks pass unless verbosity is set at package level?

**Comment by peterdesmet** [comment]
Indeed, mainly an internal function. `TRUE` is returned if there are no errors. I would name the function `check_camtrapdp()`.
