### ISSUE TITLE
How to use example created via `example_dataset()`?

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtrapdp#32]
The function `example_dataset()` is not exported at the moment (see [`NAMESPACE`](https://github.com/inbo/camtrapdp/blob/main/NAMESPACE)). 
I think it should. Otherwise we cannot use it in examples or tests of other functions like `locations()`.
@PietrH, @peterdesmet: am I right? Or am I missing something?

**Comment by peterdesmet** [comment]
Fair enough to use it in examples. I'll make it public.

**Comment by peterdesmet** [comment]
Done in f323da8e0e4258fc94da6cc50460c1d11ea25251

**Comment by PietrH** [comment]
FYI: You can use unexported functions in other functions, I'm not completely sure you can in tests.

I'm ok with setting it to public, but should we provide slightly more documentation on where `example_dataset()` comes from, and what it's for?

**Comment by peterdesmet** [comment]
The function documentation is currently https://inbo.github.io/camtrapdp/reference/example_dataset.html, so it at least indicates where it is coming from.
