### ISSUE TITLE
Use `check_package()` from frictionless in `check_camtrapdp()`

### ISSUE THREAD

**Issue by sangovae** [inbo/camtrapdp#33]
`check_package()` from frictionles is currently a private function. When made public, it should be added to `check_camtrapdp()`.
https://github.com/frictionlessdata/frictionless-r/blob/main/R/check_package.R

**Comment by peterdesmet** [comment]
Will be resolved in frictionless 1.1.0, see https://github.com/frictionlessdata/frictionless-r/pull/187
