### ISSUE TITLE
parsing failures bij inlezen laatste nieuwe export van GMU8

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#39]
bij het inlezen van de laatste export van GMU8 aan de hand van volgend commando krijg is onderstaande error:
data <- read_camtrap_dp("../../GMU8")

8 parsing failures.
  row       col   expected actual                                                                             file
16060 timestamp date like  +01:00 'C:/Users/jim_casaer/Documents/GitHub/fis-projecten/../../GMU8/observations.csv'
18433 timestamp date like  +01:00 'C:/Users/jim_casaer/Documents/GitHub/fis-projecten/../../GMU8/observations.csv'
21332 timestamp date like  +01:00 'C:/Users/jim_casaer/Documents/GitHub/fis-projecten/../../GMU8/observations.csv'
23191 timestamp date like  +01:00 'C:/Users/jim_casaer/Documents/GitHub/fis-projecten/../../GMU8/observations.csv'
55421 timestamp date like  +01:00 'C:/Users/jim_casaer/Documents/GitHub/fis-projecten/../../GMU8/observations.csv'
..... ......... .......... ...... ................................................................................
See problems(...) for more details.

**Comment by damianooldoni** [comment]
Can you type `problems()` after doing it and copy pasting all of it here? Thanks. I think I understood the error, but to be sure, I would like to have more info. Thanks.

**Comment by jimcasaer** [comment]
![image](https://user-images.githubusercontent.com/17747176/119969643-17897b00-bfaf-11eb-968f-e479b038a452.png)

**Comment by damianooldoni** [comment]
It seems some rows (16060, 18433, etc. if you check it in the csv file with a text editor, it could be that you have to check the row after, the first row contain column names and could be not counted as row, I am not sure) contain a corrupted `timestamp` as it seems it contains only what it seems to be the timezone: +01:00. You can maybe check it? You can also send me the file via mail/wetransfer.

**Comment by peterdesmet** [comment]
@jimcasaer share the file with me, it's easier to check with Frictionless

**Comment by jimcasaer** [comment]
possible reason /cause?
the are generated by Agouti - should have dates no?

**Comment by peterdesmet** [comment]
This is an Agouti error (https://git.wur.nl/y.liefting/agouti/-/issues/474), which requires manual updates in the DB. For now, it's best to remove these records from the camtrap-dp.

**Comment by damianooldoni** [comment]
thanks @peterdesmet: I close this issue as it has nothing to do with this repository.
