### ISSUE TITLE
Add taxonomy() accessory function

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtrapdp#40]
This function returns the taxonomic information from `observations(x)`.

**Comment by peterdesmet** [comment]
Two questions:

1. Should we name this `taxa()` instead?
2. Should we drop the `taxon.` prefix for the columns returned by this function?

I'm tempted to say yes to both.

**Comment by damianooldoni** [comment]
1. About function name: I understand why you prefer `taxa()`: it's a plural name as `locations()`, `observations()`etc.  So, I agree 👍 
2. In camtraptor's `read_camtrap_dp()` no prefixes were used, so removing the prefix `taxon.` will make our life while refactoring camtraptor way easier 😄 The point: do we easily can identify these columns and how likely there will be conflicts among taxonomic related columns and observations original columns in the future? I think it will be very unlikely. So, 👍 to remove the prefix.
