### ISSUE TITLE
Add examples to functions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#41]

**Comment by PietrH** [comment]
The following exported functions do not have examples:

- [ ] deployments()
- [ ] example_dataset()
- [ ] media()
- [ ] observations()
- [ ] read_camtrapdp()
- [ ] version()

**Comment by damianooldoni** [comment]
Indeed, notice some of these are implemented in PR https://github.com/inbo/camtrapdp/pull/35.
