### ISSUE TITLE
Add assignment equivalent functions `deployments() <- value` , `media() <- value` and `observations() <- value`

### ISSUE THREAD

**Issue by PietrH** [inbo/camtrapdp#42]
Similar to `purrr::pluck() <- `: https://purrr.tidyverse.org/reference/pluck.html we would like to be able to create or modify objects nested within the datapackage structure.

Using the [purrr](https://github.com/tidyverse/purrr/blob/HEAD/R/pluck.R) syntax as an example:

https://github.com/tidyverse/purrr/blob/870696c7d9f3208298ea84a36d813ffd28e59e49/R/pluck.R#L103-L108

We probably want to make use of [purrr::assign_in()](https://purrr.tidyverse.org/reference/modify_in.html)

## TODO

- [ ] `deployments(x) <-`
- [ ] `media(x) <-`
- [ ] `observations(x) <-`
- [ ] Update any reference in the code to `x$data$name_of_df <-` elsewhere in the code (e.g. [here](https://github.com/inbo/camtrapdp/blob/06946dbf91189486a06257af322f3afed9433452/R/read_camtrapdp.R#L50)).

## Scope
- The assignment functions should only assign data.frames/tibbles
- Do they need to be exported/public facing? 
- These assignment functions will provide in place assignment, and will modify the datapackage object they have as an argument
- Similar to `purrr::pluck()` I suggest they return the modified object as well

**Comment by peterdesmet** [comment]
For now, these functions can be internal.

**Comment by PietrH** [comment]
Why update https://github.com/inbo/camtrapdp/blob/06946dbf91189486a06257af322f3afed9433452/R/read_camtrapdp.R#L50 ?

**Comment by peterdesmet** [comment]
It's better to use the function `observations() <- dplyr::left_join()` than setting the property `x$data$observations` directly (as it may move in the future).
