### ISSUE TITLE
Calculate camera operation matrix

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtrapdp#44]
This issue started from #36 and aims to discuss the camOps mapping to not mix this discussion with the ongoing discussion in #36 about recordTable.

**Comment by damianooldoni** [comment]
@jimcasaer: for the [camera operation matrix](https://jniedballa.github.io/camtrapR/reference/cameraOperation.html), should I have as much rows as deployments (equivalent of camtrapR stations + sessions IDs) or do you prefer to group by locations (`location_name` or a new column, e.g. `grid` in your GMU8 example)?

**Comment by jimcasaer** [comment]
for single seasons the camera operation matrix is based on locations that equal the stations that equal our location_names
for multi seasons it is more complex -- I will have a look at it in the scripts and get back to you 

what is the session_id ?

**Comment by damianooldoni** [comment]
Finally back on this! @jimcasaer, about your last question about the `session_id` in camtrapR, I read this in [`cameraOperation()` documentation](https://jniedballa.github.io/camtrapR/reference/cameraOperation.html):

>  If several cameras were deployed per station, the matrix can contain camera- or station-specific trap operation information, or information about sessions during repeated surveys.

**Comment by damianooldoni** [comment]
@jimcasaer: I pushed a first draft. Data are grouped per location name (stations in camtrapR). Please check if this is what you have in mind. See vignette [camera-operation-matrix.html](https://inbo.github.io/camtrapdp/articles/camera-operation-matrix.html) for more details and cases.

**Comment by damianooldoni** [comment]
This issue can be closed. Camera operation matrix is generated and has already been improved by fixing #76 and #75. If other improvements are requested, please open new issues.
