### ISSUE TITLE
adding number of species as possible hover_column  in visualize_species_per_deployment

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#5]
I think it would be a good feature to be able to add n_species as hover_column in this function 
when tried to use hover_column = "n_species"
or hover_column = n_species 
this returns an error

**Comment by damianooldoni** [comment]
Sure! Good idea. 
@jimcasaer: I think it should be the default option actually. Do you agree?

**Comment by jimcasaer** [comment]
yes -- given the current name of the funtion :-)

**Comment by damianooldoni** [comment]
Issue solved, I think. Please get a look to https://inbo.github.io/camtrapdp/articles/visualize-number-of-species-per-deployment.html#create-map for example
