### ISSUE TITLE
Support `citation("camtrapdp")`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#59]
Mentioned in the README but does not work yet.

**Comment by peterdesmet** [comment]
This should be resolved once package is on CRAN, see https://github.com/r-lib/usethis/issues/806

**Comment by PietrH** [comment]
I believe this error will persist on the version of the package that is installed from github. We could include a citation.cff file if you like? 

Do we want to close this issue?

**Comment by peterdesmet** [comment]
This is resolved:

``` r
devtools::install_github("inbo/camtrapdp")
library(camtrapdp)
citation("camtrapdp")
#> 
#> To cite package 'camtrapdp' in publications use:
#> 
#>   Desmet P, Govaert S, Huybrechts P, Oldoni D (2024). _camtrapdp: Read
#>   and Manipulate Camera Trap Data Packages_.
#>   https://github.com/inbo/camtrapdp, https://inbo.github.io/camtrapdp/.
#> 
#> A BibTeX entry for LaTeX users is
#> 
#>   @Manual{,
#>     title = {camtrapdp: Read and Manipulate Camera Trap Data Packages},
#>     author = {Peter Desmet and Sanne Govaert and Pieter Huybrechts and Damiano Oldoni},
#>     year = {2024},
#>     note = {https://github.com/inbo/camtrapdp,
#> https://inbo.github.io/camtrapdp/},
#>   }
```

<sup>Created on 2024-07-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

The reason it works is because we now have a `Date` field in the DESCRIPTION (not needed if you install from CRAN, but it is needed if you use `citation()` on a development build).
