### ISSUE TITLE
deployments without observations in  visualize_species_per_deployment

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#6]
currently unclear what happens when no species were observed in a deployment

**Comment by damianooldoni** [comment]
Sure. This is still to be done. Thanks for reminder.

**Comment by damianooldoni** [comment]
@jimcasaer: How would you like to represent such deployments? A circle with 0 radius is by definition not visible? 
Maybe a specific circle color?

**Comment by jimcasaer** [comment]
white ?

Op vr 19 mrt. 2021 15:07 schreef Damiano Oldoni ***@***.***>:

**Comment by damianooldoni** [comment]
Done together with some other things (see #8). Get a view to the updated vignette: https://inbo.github.io/camtrapdp/articles/visualize-number-of-species-per-deployment.html

I opted for grey color for this kind of deployments and I use white as for value 0, i.e. observation of unidentified species only.

**Comment by damianooldoni** [comment]
While working on #229 I noticed that `map_dep()` is not making distinctions between 0 and NA at the moment. I reopen this issue. We are using an icon (a black `x` by default) for 0 values. My idea is to use another icon for NA values, by default a red x. The user is allowed to customize how to visualize NA values  by using three args very similar to the ones for zero values: 
- `na_values_show`
- `na_values_icon_url`
- `na_values_icon_size`

**Comment by damianooldoni** [comment]
Just few screenshots to give an idea:

![image](https://github.com/inbo/camtraptor/assets/33662631/3c274a60-64d8-4d9f-9cf2-c0ddd4193a2b)


![image](https://github.com/inbo/camtraptor/assets/33662631/59e9ef21-083e-44ae-9075-37d4e8798911)

![image](https://github.com/inbo/camtraptor/assets/33662631/aaa109d4-f307-4665-a41d-738a896ca2cf)
