### ISSUE TITLE
Faster `read_camtrap_dp()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#6]
In the new Camtrap DP format, observations no longer have a `deploymentID`.  That means that any join between observations and deployments has to be done over media, which can be costly. @PietrH and I discussed how this could be implemented in an efficient way in camtraptor.

## read_camtrap_dp()

1. Reads a `datapackage.json` and stores as a "package" list object (same as now)
2. Reads resources from disk with `frictionless::read_resource()` (same as now)
3. ~Creates a joined dataframe: deployments > media > observations + distinct by `eventID`. This could be done with dplyr or data.table (**new**)~

**Creating a single df is a bad idea, see https://github.com/inbo/camtraptor/issues/202#issuecomment-1516160240. Rather, keep tables separate, but include tables for sequences, locations, taxonomy (cf https://wec.wur.nl/r/ctdp/)**

4. ~Attaches the joined dataframe to the package, e.g. at `$data` (**new**)~
5. ~No longer stores `$data$deployments`, `$data$media`, `$data$observations` to save memory (**new**)~
6. Returns the package (same as now)

## filter()

1. Masks `dplyr::filter()` for a camtrap dp object (#92)
2. Uses `dplyr::filter()` (or data.table) on `$data` under the hood
3. Can optionally also filter the `spatial`, `temporal` and `taxonomic` scope in the metadata

## other functions

1. Typically make use of `$data` rather than `$data$deployments`, ...
2. Can still access `media` or other resources if they need to (by reading from disk)

**Comment by damianooldoni** [comment]
I would close this issue as the reason behind it:

> In the new Camtrap DP format, observations no longer have a deploymentID.

is not true anymore. @peterdesmet: do you agree?

**Comment by peterdesmet** [comment]
Agreed.
