### ISSUE TITLE
taxonID and scientificName

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#61]
read_camtrap_dp returns error Problem with `taxon_id` and `scientific_name`.
due to fact that taxon_id and scientific_name were replaced by
taxonID and scientifcName 

=> should be adapted in read_camptrap_dp function of the package

**Comment by damianooldoni** [comment]
Thanks @jimcasaer: this is something already mentioned in #59.

**Comment by jimcasaer** [comment]
@damianooldoni can this be handled with urgency? - it is hindering the easy use of the package given that it is in one of the first steps

**Comment by damianooldoni** [comment]
I understand. I will do my best!

**Comment by damianooldoni** [comment]
Solved! 🥳
