### ISSUE TITLE
Add `write_eml()`

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtrapdp#61]
Hi! While working on camtraptor version 1.0, I am going to remove `write_dwc()` (and associated file `write_dwc.R`) in camtraptor as this functionality has been transferred to camtrapdp, see #55. 

Questions:
1. Can I remove function from camtraptor as well?
2. Will `write_eml()` be implemented in camtrapdp as well?

**Comment by peterdesmet** [comment]
1. Yes, can be removed.
2. No, there is no longer a need for this function, since the IPT can now natively publish Camtrap DP (so no metadata conversion to EML is needed).

**Comment by peterdesmet** [comment]
@sannegovaert since you have worked on the movepub `write_eml()`, could you tackle this one. Note: the function should not have any arguments (beyond `x` and `directory`) as it needs to work as part of GBIF processing without human interaction. Ping/chat me if you have questions.
