### ISSUE TITLE
rename datapackage to frictionless-r

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtrapdp#64]
The datapackage R package is now under the frictionless hat and is called frictionless-r. The previous inbo/datapackage repo points now to https://github.com/frictionlessdata/frictionless-r

We need to import it by `library(frictionless-r)`

**Comment by peterdesmet** [comment]
Notice that you need to install with `library(frictionless)` (no `-r`)

**Comment by damianooldoni** [comment]
Done in https://github.com/inbo/camtrapdp/pull/66
