### ISSUE TITLE
create function get_custom_effort

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#70]
function that calculates the effort for a specific time within the survey

variables are:

startdate (default = min startdate from all depl)
enddate (default = max enddate from all depl)
unit (hours, days, default = hours)
group_by(day, week, month, year -- default = null (total from startdata till enddata)

* returns the effort for each group_by in the chosen units

**Comment by LynnINBO** [comment]
Created branch 70-custom-trap-effort

**Comment by LynnINBO** [comment]
@damianooldoni Wrote a rough first draft of the function based on the test code I applied to our datasets. I doubt it's gonna work as is, but it could be a start.
