### ISSUE TITLE
Create `merge()` to merge datasets

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#75]
Note by @peterdesmet: see https://github.com/inbo/camtrapdp/issues/75#issuecomment-2142308577 for recent thoughts.

---

Quite often we want to merge the exports of several research projects (more and more for multi-site research), all using Camtrap-DP as export format, mostly all resulting from agouti.
Though manually this can be done by using several times read_camtrap_dp and subsequently merging the different resulting csv-files, I was wondering if it would not be better to add a function to camtraptor that automatically 

- [ ] merges different data packages resulting from read_camtrap_dp
- [ ] adds a column to the deployments.csv using the project_name as variable
- [ ] adds a column to the deployments.csv using the project location / study site 
- [ ] the function name could be "join_exports" or something similar but this I leave up to Peter :-)

**Comment by peterdesmet** [comment]
I have described the functionality in more detail at https://github.com/tdwg/camtrap-dp/issues/380. I think the function should be called `merge_camtrapdp()`.

**Comment by peterdesmet** [comment]
Task list by @sannegovaert:

- [x] Deployments: combination of deployments (but check that deploymentID remains unique)
- [x] Media: combination of media (but check that mediaID remains unique)
- [x] Observations: combination of media (but check that observationID remains unique)
- [x] [name](https://camtrap-dp.tdwg.org/metadata/#name): a new name is created (old values are not retained)
- [x] [id](https://camtrap-dp.tdwg.org/metadata/#id): a new ID is created. The original ids are stored in [relatedIdentifiers](https://camtrap-dp.tdwg.org/metadata/#relatedIdentifiers)
- [x] [created](https://camtrap-dp.tdwg.org/metadata/#created): reset to current timestamp (old values are not retained)
- [x] [title](https://camtrap-dp.tdwg.org/metadata/#title): a new title (old values are not retained)
- [x] [contributors](https://camtrap-dp.tdwg.org/metadata/#contributors): a combination is made, duplicates (on some or all fields) are removed and roles are combined (in Frictionless v2). The order is not retained.
- [ ] [description](https://camtrap-dp.tdwg.org/metadata/#description): a new one is generated, potentially still listing the previous descriptions
- [x] [version](https://camtrap-dp.tdwg.org/metadata/#version): is reset to 1.0 (old values are not retained)
- [x] [keywords](https://camtrap-dp.tdwg.org/metadata/#keywords): a combination is made, duplicates are removed
- [x] [image](https://camtrap-dp.tdwg.org/metadata/#image): is removed (old values are not retained)
- [x] [homepage](https://camtrap-dp.tdwg.org/metadata/#homepage): is removed (old values are not retained)
- [x] [sources](https://camtrap-dp.tdwg.org/metadata/#sources): a combination is made, duplicates are removed
- [x] [licenses](https://camtrap-dp.tdwg.org/metadata/#licenses): a combination is made, duplicates are removed. If e.g. two different license with scope: media are listed, it won't be clear which one applies to which media.
- [x] [bibliographicCitation](https://camtrap-dp.tdwg.org/metadata/#bibliographicCitation): is removed (old values are not retained)
- [ ] [project](https://camtrap-dp.tdwg.org/metadata/#project): ideally this becomes an array of projects and deployments have a projectID to link to the correct project info.
- [x] [coordinatePrecision](https://camtrap-dp.tdwg.org/metadata/#coordinatePrecision): is reset to least precise precision (old values are not retained)
- [x] [spatial](https://camtrap-dp.tdwg.org/metadata/#spatial): is reset based on new deployments (old values are not retained)
- [x] [temporal](https://camtrap-dp.tdwg.org/metadata/#temporal): is reset based on new deployments (old vales are not retained)
- [x] [taxonomic](https://camtrap-dp.tdwg.org/metadata/#taxonomic): a combination is made, duplicates are removed.
- [x] [relatedIdentifiers](https://camtrap-dp.tdwg.org/metadata/#relatedIdentifiers): a combination is made, duplicates are removed
- [ ] [references](https://camtrap-dp.tdwg.org/metadata/#references): a combination is made, duplicates are removed

**Comment by peterdesmet** [comment]
Merge should also handle "additional resources". Currently only the additional resource of x are kept

- Keeping both makes sense, but if they are named the same, we don't know what to do
- Even if we keep them, they might contain identifiers that refer to dep, med, obs which become invalid

I think that the cleanest solution is therefore to remove additional resources, with a warning that lists which ones are removed, see this code to find them:

https://github.com/inbo/camtrapdp/blob/8c4981e39ed56245630d6ed2a4ac66f282c84a59/R/print.R#L42

In the tests, I would remove `individuals` from `x` so you don't have to deal with `suppressWarnings()` all the time.

**Comment by peterdesmet** [comment]
> Could you prompt the user if they are named the same?

As in, ask for a decision? What options do you provide them?

One alternative is to rename the additional resources by prefixes the dataset identifier (cf. the deployments). I would then do this for all resources, so you see where they came from). This doesn't prompt user.

**Comment by PietrH** [comment]
If they are named the same, ask the user to name the tables. 

I think there is value in being consistent with the deployments.
