### ISSUE TITLE
allow selection of column to create station in get_cam_op

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#76]
as far as I get it right now the function uses always the location column to generate the station ? 
is perfect as default but flexibility would be required => make column a specification in function

**Comment by damianooldoni** [comment]
Yes, definitely a sensible request 👍

**Comment by damianooldoni** [comment]
Solved by adding argument `station_col` to `get_cam_op()`. Default: column name `"locationName"`.
You can also decide to add prefix `Station` to the row names of the matrix (as returned by camtrapR's function) by setting argument `use_prefix = TRUE`. Default: `FALSE`. See https://inbo.github.io/camtrapdp/articles/camera-operation-matrix.html#station-names for more details.
