### ISSUE TITLE
Allow `digits = NULL` to leave coordinates as is, but set uncertainty to 30 in `round_coordinates()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#76]
Coordinate uncertainty is often NULL in a Camtrap DP. We could use `round_coordinates()` to allow users to set it to the default (for GPS) of 30 m without rounding the coordinates.

**Comment by sannegovaert** [comment]
I see 2 options when digits = NULL:
1) `dplyr::mutate(coordinateUncertainty = 30)`
2) ```
dplyr::mutate(
          coordinateUncertainty = dplyr::case_when(
            is.na(coordinateUncertainty) ~ 30,
            is.null(coordinateUncertainty) ~ 30,
            .default = coordinateUncertainty)
        )
```

Which one  do you prefer, @peterdesmet @damianooldoni @PietrH ?

**Comment by peterdesmet** [comment]
I'm now wondering if we should even offer this functionality. It's a bit odd to handle it via a `round_coordinates()` function, which then assumes it should be 30. Users should likely do this themselves with a `dplyr::mutate()`.

If we do it, then I think we should keep any none NA values. I don't think we will have NULL values, so a `if_else()` is sufficient.

**Comment by PietrH** [comment]
I agree to leave this up to users and dplyr

**Comment by peterdesmet** [comment]
Then we can close this issue. :-)
