### ISSUE TITLE
Update `read_camtrap_dp()` to support Camtrap DP v1.0 onwards with `convert_` functions 

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#9]
_Suggested in camtraptor July 2023 coding sprint_

See inbo/camtraptor#251 for background. We plan to support all legacy versions of Camtrap DP from version 1.0 onwards.

This will be done by `read_camtrap_dp()` which can detect the used version and run the profile and data through a number of `convert_` functions to get it to the latest versions, e.g.:

```R
# package == v1.0 and since then there is a version 1.1, 1.2
package <- convert_1.0_to_1.1(package)
package <- convert_1.1_to_1.2(package)
package <- convert_1.2_to_1.3(package)
```

Working sequentially avoids us from having to repeat the same conversions over and over again. It also makes it easier to notice what has changed between versions.

If a certain step is more cumbersome to do via an intermediate version, it is possible to create a conversion function that skips a number of versions, e.g. `convert_1.0_to_1.2()`. The existing number of convert functions would then be:

```ini
# convert_1.0_to_1.1() deleted
convert_1.0_to_1.2()
convert_1.2_to_1.3()
```

This specific conversion functions could be all handled by a generic

```
convert(package)
```

This function would:

- Get the dataframes and attach these to `$data`
- Read the version
- Call the required number of `convert_` functions on the data frames **and profile (metadata)**
- Return the package

**Comment by damianooldoni** [comment]
At the moment we are at version 1.0, so none of the `convert_1.x_to_1.y()` functions need to be implemented. In other words:
- `read_camtrap_dp()` calls `convert()`.
- `convert()` controls the version via `get_version()` and in case of a valid supported version (= 1.0) will return the package as it is at the moment.

**Comment by peterdesmet** [comment]
Correct. The template for conversion functions is ready in https://github.com/inbo/camtrapdp/blob/9ecceb07ff50a2fd243e28c2584ddc417ef9a51f/R/convert.R

**Comment by damianooldoni** [comment]
I see you added a convert step from 0.1.6 to 1.0. Didn't we decide to start converting from 1.0 onwards? In https://github.com/inbo/camtraptor/issues/251:
 > Supporting all legacy versions of Camtrap DP from version 1.0-rc.1 onwards. This means we will drop support for v0.1.6. Users will be able to recreate their exports in the latest version of Camtrap DP in Agouti and Trapper.

**Comment by peterdesmet** [comment]
Yes, correct. the function is currently only there as an example for future me and co-developers. It is never called, since `read_camtrap_dp()` doesn't allow other versions than 1.0.
