### ISSUE TITLE
Improve info shown while hovering

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtrapdp#9]
@damianooldoni I was wondering if it would not be good to make the hovering showing location / month / year of the deployment as well as number of species 

same logic can later be extended to number observations / number of animals / RAI for a specific species

_Originally posted by @jimcasaer in https://github.com/inbo/camtrapdp/issues/8#issuecomment-804191275_

**Comment by damianooldoni** [comment]
Do you mean location OR month OR year OR n of species? 
Or do you mean location AND month AND year AND n of species?
Or do you mean location AND/OR month AND/OR year AND/OR n of species?

I vote for third one. About month and year, you mean start-end date of the deployment, right?

**Comment by jimcasaer** [comment]
third one is perfect 
was wondering is presenting start_date and/of end_date of the deployment is not more logic than year and /or month

**Comment by damianooldoni** [comment]
@jimcasaer, see updated documentation: https://inbo.github.io/camtrapdp/articles/visualize-deployment-features.html and let me know.
